# Generated by Django 4.2 on 2023-05-01 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('author_name', models.CharField(max_length=50, verbose_name='Автор')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='Цена')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Книги',
                'verbose_name_plural': 'Книги',
                'ordering': ['-name', 'price'],
            },
        ),
    ]
