# Generated by Django 4.2 on 2023-04-22 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_category_book_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категории', 'verbose_name_plural': 'Категории'},
        ),
    ]
