# Generated by Django 4.2 on 2023-04-12 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_image_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='book',
        ),
    ]
