# Generated by Django 4.2 on 2023-04-17 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_image_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['title', 'book'], 'verbose_name': 'Картинки', 'verbose_name_plural': 'Картинки'},
        ),
    ]
