# Generated by Django 4.2 on 2023-04-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_image_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static_images')),
            ],
            options={
                'verbose_name': 'Статические картинки',
                'verbose_name_plural': 'Статические картинки',
            },
        ),
    ]
